const fs = require("fs");
let c = fs.readFileSync("./src/lib/translations.ts", "utf8");

// Split to find where AR section starts
const arMatch = c.match(/\nexport const ar: Record<TranslationKey, string> = \{[\s\S]*?\n\};(\n|$)/);
if (!arMatch) {
  console.log("Could not find AR section");
  process.exit(1);
}

// Full Arabic translations for all original FR keys
const arTranslations = {
  "nav.accueil": "الرئيسية",
  "nav.formation": "التكوين",
  "nav.formations": "التكوينات",
  "nav.modules": "الوحدات",
  "nav.blog": "المدونة",
  "nav.tarifs": "الأسعار",
  "nav.rechercher": "بحث",
  "nav.connexion": "تسجيل الدخول",
  "nav.rejoindre": "انضم إلينا",
  "nav.menu": "القائمة",
  "nav.fermer": "إغلاق",
  "nav.voirFormations": "عرض التكوينات",
  "nav.accederAcademie": "دخول الأكاديمية ←",
  "footer.tagline": "حوّل أفكارك إلى شركة ناشئة بفضل الذكاء الاصطناعي.",
  "footer.formation": "التكوين",
  "footer.ressources": "الموارد",
  "footer.legal": "قانوني",
  "footer.iaGratuite": "ذكاء اصطناعي مجاني",
  "footer.vibeCoding": "Vibe Coding",
  "footer.saas": "SaaS",
  "footer.agentsIA": "وكلاء الذكاء الاصطناعي",
  "footer.noCode": "بدون برمجة",
  "footer.startup": "الشركات الناشئة",
  "footer.blog": "المدونة",
  "footer.faq": "الأسئلة الشائعة",
  "footer.contact": "اتصل بنا",
  "footer.aPropos": "من نحن",
  "footer.cgu": "شروط الاستخدام",
  "footer.mentionsLegales": "الإشعار القانوني",
  "footer.faitAlgerie": "صنع في الجزائر · طموح عالمي",
  "hero.badge": "✦ أكاديمية ديجيتال إكس سوليوشنز · دفعة 2026",
  "hero.ligne1": "الذكاء الاصطناعي",
  "hero.ligne2": "لم يعد مستقبلاً.",
  "hero.ligne3": "إنه الحاضر.",
  "hero.descMobile": "أكاديمية ديجيتال إكس سوليوشنز هي مجتمع خاص يهدف إلى جعل تقنيات الذكاء الاصطناعي في متناول جميع الجزائريين.",
  "hero.descDesktop": "أكاديمية ديجيتال إكس سوليوشنز هي مجتمع خاص يهدف إلى جعل تقنيات الذكاء الاصطناعي في متناول جميع الجزائريين. تعلّم إتقان الأدوات والأساليب والمهارات التي تشكل عالم الغد بالفعل.",
  "hero.apprenants": "★★★★★ {count} متعلّم · الجزائر والعالم",
  "hero.plusOutils": "+ 30 أداة وتقنية أخرى في البرنامج",
  "landing.modules.badge": "مسار 2026",
  "landing.modules.titre": "{count} تكوينات. تحوّل كامل.",
  "landing.modules.sousTitre": "من التمهيد في الذكاء الاصطناعي إلى إطلاق شركتك الناشئة، كل تكوين صُمّم ليدفعك إلى الفعل.",
  "landing.modules.statFormations": "تكويناً",
  "landing.modules.statVideos": "فيديو",
  "landing.modules.statCertificat": "شهادة عند الإتمام",
  "landing.modules.videos": "فيديو",
  "landing.modules.module": "الوحدة",
  "landing.modules.debutant": "مبتدئ",
  "landing.modules.intermediaire": "متوسط",
  "landing.modules.avance": "متقدم",
  "landing.modules.tous": "الجميع",
  "pricing.eyebrow": "الاستثمار",
  "pricing.titre": "وصول كامل. سعر واحد.",
  "pricing.sousTitre": "لا خطط معقدة. تدفع مرة واحدة، وتحصل على كل شيء.",
  "pricing.accesComplet": "وصول كامل",
  "pricing.description": "أنت لا تدفع ثمن تكوين فقط. أنت تحصل على وصول إلى نظامنا البيئي بأكمله: التكوينات، المساعد بالذكاء الاصطناعي، المجتمع، المكتبة والدعم. كل ذلك لبناء شركتك الناشئة.",
  "pricing.cta": "الوصول الآن",
  "pricing.feature1": "وصول كامل إلى جميع تكويناتنا",
  "pricing.feature2": "ديجيتال إكس أي — مساعدك بالذكاء الاصطناعي الذي يبرمج ويحلل ويبني لك",
  "pricing.feature3": "مجتمع خاص بأكثر من 1200 عضو نشط",
  "pricing.feature4": "المكتبة: وثائق، برومبتات، جيت هاب، مشاريع",
  "pricing.feature5": "شهادة رسمية من أكاديمية ديجيتال إكس سوليوشنز",
  "pricing.feature6": "دعم 7/7 — نرد دائماً",
  "pricing.feature7": "تحديثات مجانية مدى الحياة",
  "pricing.feature8": "وصول مبكر إلى الجديد",
  "pricing.garantie1": "رضاك أو استرداد أموالك خلال 7 أيام",
  "pricing.garantie2": "لا التزام — ألغِ متى شئت",
  "pricing.garantie3": "دفعة واحدة — لا اشتراك",
  "faq.eyebrow": "الأسئلة",
  "faq.titre": "الأسئلة الشائعة",
  "faq.sousTitre": "كل ما تريد معرفته قبل الانضمام إلى المغامرة",
  "faq.q1": "هل تحتاج إلى معرفة مسبقة؟",
  "faq.r1": "لا، التكوين مصمم لجميع المستويات. تبدأ كل وحدة بالأساسيات وتتقدم نحو المفاهيم المتقدمة. الفضول والتحفيز هما المتطلبان الوحيدان.",
  "faq.q2": "كم تستغرق مدة التكوين؟",
  "faq.r2": "يمثل التكوين الكامل حوالي 40 ساعة من المحتوى المرئي، يمكن متابعته وفقاً لسرعتك الخاصة. معظم المتعلمين ينهونه في 8 إلى 12 أسبوعاً.",
  "faq.q3": "هل الذكاء الاصطناعي مجاني حقاً وغير محدود؟",
  "faq.r3": "نعم! نمنحك وصولاً إلى أقوى النماذج (GPT-4، Claude، Gemini) بدون اشتراك. يمكنك استخدامها بقدر ما تريد في إطار التكوين.",
  "faq.q4": "هل هناك مرافقة؟",
  "faq.r4": "نعم، ستحصل على وصول إلى مجتمعنا النشط في ديسكورد، جلسات أسئلة وأجوبة منتظمة، ومساعد ذكاء اصطناعي مدمج في المنصة لمساعدتك 24/24.",
  "faq.q5": "هل يتم تحديث التكوين؟",
  "faq.r5": "بالتأكيد. يتم تحديث المحتوى بانتظام لمواكبة التطور السريع لتقنيات الذكاء الاصطناعي. التحديثات مشمولة مدى الحياة.",
  "faq.q6": "هل يمكنني الدفع على أقساط؟",
  "faq.r6": "اتصل بفريقنا لمناقشة خيارات الدفع المناسبة لوضعك.",
  "team.eyebrow": "الفريق",
  "team.titre": "وراء ديجيتال إكس",
  "team.sousTitre": "فريق شغوف بالذكاء الاصطناعي والتكوين وريادة الأعمال في الجزائر.",
  "team.membre1.nom": "كريم بن زمة",
  "team.membre1.role": "المؤسس المشارك ومدرب الذكاء الاصطناعي",
  "team.membre1.desc": "خبير في الذكاء الاصطناعي وتطوير SaaS. مدرب شغوف بنقل المهارات التقنية.",
  "team.membre2.nom": "أمين شريف",
  "team.membre2.role": "المؤسس المشارك ومطور Full-Stack",
  "team.membre2.desc": "مطور Full-Stack بخبرة تزيد عن 10 سنوات. متخصص في هندسة السحابة والأتمتة.",
  "stats.apprenants": "متعلّم",
  "stats.heures": "ساعة تدريبية",
  "stats.projets": "مشروع منجز",
  "stats.satisfaction": "رضا",
  "blog.titre": "المدونة",
  "blog.sousTitre": "مقالات، أدلة وبرامج تعليمية لإتقان الذكاء الاصطناعي والتطوير الحديث",
  "blog.lirePlus": "اقرأ المزيد",
  "contact.titre": "اتصل بنا",
  "contact.sousTitre": "لديك سؤال؟ اكتب لنا",
  "contact.nom": "الاسم",
  "contact.email": "البريد الإلكتروني",
  "contact.message": "الرسالة",
  "contact.envoyer": "إرسال",
  "auth.retour": "رجوع",
  "auth.connexion": "تسجيل الدخول",
  "auth.inscription": "التسجيل",
  "auth.email": "البريد الإلكتروني",
  "auth.motDePasse": "كلمة المرور",
  "auth.nomComplet": "الاسم الكامل",
  "auth.seConnecter": "تسجيل الدخول",
  "auth.creerCompte": "إنشاء حساب",
  "auth.pasDeCompte": "ليس لديك حساب بعد؟",
  "auth.dejaCompte": "لديك حساب بالفعل؟",
  "auth.mdpOublie": "نسيت كلمة المرور؟",
  "auth.envoyerLien": "إرسال الرابط",
  "auth.deconnexion": "تسجيل الخروج",
  "auth.codeValidation": "رمز التحقق",
  "auth.entrezCode": "أدخل رمزك",
  "auth.activerCompte": "تفعيل حسابي",
  "auth.validationEnCours": "جارٍ التحقق...",
  "dashboard.accueil": "الرئيسية",
  "dashboard.mesFormations": "تكويناتي",
  "dashboard.nosFormations": "تكويناتنا",
  "dashboard.bibliotheque": "المكتبة",
  "dashboard.communaute": "المجتمع",
  "dashboard.assistantIA": "المساعد بالذكاء الاصطناعي",
  "dashboard.digitalXIA": "ديجيتال إكس أي",
  "dashboard.certificats": "الشهادات",
  "dashboard.parametres": "الإعدادات",
  "dashboard.admin": "الإدارة",
  "dashboard.seDeconnecter": "تسجيل الخروج",
  "dashboard.profil": "الملف الشخصي",
  "dashboard.rechercher": "بحث",
  "dashboard.videosVisionnees": "فيديو تمت مشاهدته",
  "dashboard.tempsTotal": "الوقت الإجمالي",
  "dashboard.progressionGlobale": "التقدم العام",
  "dashboard.certificatsObtenus": "الشهادات",
  "dashboard.progression": "التقدم",
  "dashboard.modules": "وحدات",
  "dashboard.termines": "مكتملة",
  "dashboard.enCours": "قيد التقدم",
  "dashboard.parcours": "المسار",
  "dashboard.voirTout": "عرض الكل",
  "dashboard.badges": "الشارات",
  "dashboard.joursConsecutifs": "يوم متتابع",
  "dashboard.niveau": "المستوى",
  "dashboard.commencezFormation": "ابدأ تكوينك",
  "dashboard.aucuneFormation": "لا توجد تكوينات متاحة حالياً",
  "dashboard.formationsEnCours": "التكوينات قيد التقدم",
  "dashboard.continuer": "استمر",
  "module.retourFormation": "العودة إلى التكوين",
  "module.videos": "فيديو",
  "module.listeVideos": "قائمة الفيديوهات",
  "module.ressources": "الموارد",
  "module.aucuneRessource": "لا توجد موارد لهذه الوحدة",
  "module.nonTrouve": "الوحدة غير موجودة",
  "module.regarderVideo": "مشاهدة الفيديو",
  "module.completeSur": "مكتمل",
  "module.progress": "التقدم",
  "watch.retourModule": "العودة إلى الوحدة",
  "watch.termine": "مكتمل",
  "watch.marquerVu": "تحديد كمُشاهَد",
  "watch.marquerNonVu": "تحديد كغير مُشاهَد",
  "watch.suivant": "التالي",
  "watch.videoNonTrouvee": "الفيديو غير موجود",
  "watch.ressourcesModule": "موارد الوحدة",
  "watch.questionIA": "طرح سؤال على الذكاء الاصطناعي",
  "watch.listeVideos": "قائمة الفيديوهات",
  "bibli.titre": "المكتبة",
  "bibli.sousTitre": "الموارد، البرومبتات، القوالب والبرامج النصية لطلابنا",
  "bibli.rechercher": "ابحث عن مورد...",
  "bibli.tout": "الكل",
  "bibli.skillsJARVIS": "⚡ مهارات JARVIS",
  "bibli.skillsDesc": "ملفات تعليمات جاهزة لـ Claude Code. حمّلها وضعها في مشروعك وفعّل قدرات خارقة: التوجيه الذكي، التعلم التلقائي، المهارات المتقدمة وغيرها.",
  "bibli.aucuneRessource": "لم يتم العثور على أي مورد",
  "bibli.ouvrir": "فتح",
  "bibli.copier": "نسخ",
  "bibli.telechargerSkill": "⚡ تحميل المهارة",
  "bibli.voirGitHub": "عرض على GitHub",
  "bibli.module": "الوحدة",
  "communaute.titre": "المجتمع",
  "communaute.sousTitre": "تبادل مع المتعلمين الآخرين وشارك مشاريعك",
  "communaute.membres": "الأعضاء",
  "communaute.discussions": "النقاشات",
  "communaute.enLigne": "متصل",
  "communaute.tousCanaux": "جميع القنوات",
  "communaute.general": "عام",
  "communaute.entraide": "مساعدة",
  "communaute.ressources": "موارد",
  "communaute.succes": "نجاحات",
  "communaute.placeholder": "شارك شيئاً مع المجتمع...",
  "communaute.publier": "نشر",
  "communaute.aucunPost": "لا توجد منشورات في هذه القناة",
  "communaute.commenter": "تعليق",
  "ai.titre": "المساعد بالذكاء الاصطناعي",
  "ai.nouvelleConversation": "محادثة جديدة",
  "ai.placeholder": "اطرح سؤالك، {name}...",
  "ai.suggest1": "اشرح لي Vibe Coding",
  "ai.suggest2": "كيف أطلق SaaS؟",
  "ai.suggest3": "نصائح لبدء n8n",
  "ai.suggest4": "ما هو Agent IA؟",
  "ai.description": "مساعد تعليمي مخصص لتكوينات أكاديمية ديجيتال إكس سوليوشنز. اطرح أسئلتك حول الدروس والبرمجة والمشاريع.",
  "ai.disclaimer": "قد يخطئ ديجيتال إكس أي. تحقق من المعلومات المهمة.",
  "ai.indisponible": "عذراً، خدمة الذكاء الاصطناعي غير متاحة حالياً.",
  "ai.configuration": "خدمة الذكاء الاصطناعي قيد الإعداد. اتصل بالدعم.",
  "certificats.titre": "الشهادات",
  "certificats.sousTitre": "حمّل شهادات نجاحك",
  "certificats.obtenus": "شهادة محصل عليها",
  "certificats.verrouille": "مقفل",
  "certificats.pdf": "PDF",
  "certificats.completeSur": "مكتمل 100%",
  "param.titre": "الإعدادات",
  "param.sousTitre": "إدارة حسابك وتفضيلاتك",
  "param.profil": "الملف الشخصي",
  "param.notifications": "الإشعارات",
  "param.parrainage": "الإحالة",
  "param.securite": "الأمان",
  "param.infosPersonnelles": "المعلومات الشخصية",
  "param.nomComplet": "الاسم الكامل",
  "param.email": "البريد الإلكتروني",
  "param.enregistrer": "حفظ",
  "param.enregistre": "تم الحفظ",
  "param.prefsNotifs": "تفضيلات الإشعارات",
  "param.notif1": "دروس أو وحدات جديدة",
  "param.notif1Desc": "تلقي إشعار عند إضافة محتوى جديد",
  "param.notif2": "تذكيرات التقدم",
  "param.notif2Desc": "تلقي تذكيرات لمواصلة تكوينك",
  "param.notif3": "رسائل المجتمع",
  "param.notif3Desc": "إشعارات عندما يتفاعل أحدهم مع منشوراتك",
  "param.notif4": "العروض والتحديثات",
  "param.notif4Desc": "معلومات حول الميزات الجديدة",
  "param.securiteCompte": "أمان الحساب",
  "param.motDePasse": "كلمة المرور",
  "param.modifier": "تعديل",
  "param.sessionActive": "الجلسة النشطة",
  "param.connecte": "متصل",
  "param.codeParrainage": "رمز الإحالة الخاص بك",
  "param.copier": "نسخ",
  "param.copie": "تم النسخ!",
  "param.personnesParrainees": "شخص تمت إحالته",
  "param.xpGagnes": "نقاط خبرة مكتسبة (100 XP لكل مُحال)",
  "param.partagezSur": "شارك على:",
  "param.codeInaccessible": "تعذر تحميل رمزك. حاول مرة أخرى لاحقاً.",
  "param.deconnexion": "جارٍ تسجيل الخروج...",
  "param.utilisateur": "مستخدم",
  "admin.vueEnsemble": "نظرة عامة",
  "admin.tableauBord": "لوحة تحكم المشرف",
  "admin.totalInscrits": "إجمالي المسجلين",
  "admin.enAttente": "قيد الانتظار",
  "admin.actifs": "نشط",
  "admin.administrateurs": "المشرفون",
  "admin.inscriptions7j": "التسجيلات (آخر 7 أيام)",
  "admin.demandesRecent": "الطلبات الأخيرة",
  "admin.aucuneDemande": "لا توجد طلبات معلقة",
  "admin.codesAcces": "رموز الوصول",
  "admin.codesActifs": "رمز نشط",
  "admin.utilisations": "استخدام",
  "admin.genererCode": "توليد رمز",
  "admin.totalCodes": "إجمالي الرموز",
  "admin.inscriptions": "التسجيلات",
  "admin.approuver": "قبول",
  "admin.refuser": "رفض",
  "admin.approuverInscription": "قبول التسجيل",
  "admin.activerCompte": "تفعيل حساب {name}",
  "admin.compteActive": "تم تفعيل الحساب!",
  "admin.codeGenere": "رمز الوصول المُنشأ لـ {name}:",
  "admin.termine": "تم",
  "admin.refuserInscription": "رفض التسجيل",
  "admin.supprimerDefinitivement": "حذف نهائي",
  "admin.annuler": "إلغاء",
  "admin.rechercher": "بحث...",
  "admin.toutes": "الكل",
  "admin.approuvees": "مقبولة",
  "admin.refusees": "مرفوضة",
  "admin.videos": "الفيديوهات",
  "admin.ajouterVideo": "إضافة فيديو",
  "admin.statistiques": "الإحصائيات",
  "admin.donneesReelles": "بيانات حقيقية للمنصة",
  "admin.modifier": "تعديل",
  "admin.supprimer": "حذف",
  "admin.tousModules": "جميع الوحدات",
  "validation.bienvenue": "مرحباً بك في {name}",
  "validation.description": "حيث مستقبلك في انتظارك ✨",
  "validation.compteEnAttente": "الحساب قيد انتظار التحقق",
  "validation.explication": "تم إنشاء حسابك {email} بنجاح لكنه غير نشط بعد. بمجرد تأكيد دفعتك، سيرسل لك فريقنا رمز التحقق عبر البريد الإلكتروني. أدخله أدناه لتفعيل وصولك إلى التكوين. 🚀",
  "validation.codeValidation": "رمز التحقق",
  "validation.entrezCode": "أدخل رمزك",
  "validation.activerCompte": "تفعيل حسابي",
  "validation.validationEnCours": "جارٍ التحقق...",
  "validation.seDeconnecter": "تسجيل الخروج",
  "gamification.apprentiIA": "مبتدئ الذكاء الاصطناعي",
  "gamification.vibeCoder": "مبرمج Vibe",
  "gamification.fondateur": "مؤسس",
  "gamification.architecteIA": "مهندس ذكاء اصطناعي",
  "gamification.maitre": "أستاذ",
  "error.nonAuthentifie": "غير موثّق",
  "error.accesRefuse": "تم رفض الوصول",
  "error.tropTentatives": "محاولات كثيرة جداً. حاول مرة أخرى بعد دقيقة.",
  "error.profilIntrouvable": "الملف الشخصي غير موجود",
  "error.codeInvalide": "رمز غير صالح. تحقق من رمزك وحاول مرة أخرى.",
  "error.activation": "خطأ أثناء التفعيل",
  "error.serviceIndisponible": "خدمة الذكاء الاصطناعي غير متاحة",
  "error.requis": " مطلوب",
  "error.generique": "حدث خطأ. حاول مرة أخرى.",
  "langue.francais": "Français",
  "langue.arabe": "العربية",
  "langue.switch": "اللغة",
};

// Build the full AR section
let entries = Object.keys(arTranslations);
let lines = entries.map(k => {
  let v = arTranslations[k].replace(/"/g, '\\"');
  return `  "${k}": "${v}"`;
});

const arSection = "\nexport const ar: Record<TranslationKey, string> = {\n" + lines.join(",\n") + ",\n};\nexport type I18nDict = typeof fr;\n";

// Find and replace the current AR section
const currentArMatch = c.match(/\nexport const ar: Record<TranslationKey, string> = \{[\s\S]*?\n\};(\nexport type I18nDict = typeof fr;\n)?/);
if (currentArMatch) {
  c = c.replace(currentArMatch[0], arSection);
  fs.writeFileSync("./src/lib/translations.ts", c);
  console.log("✅ AR section rebuilt with", entries.length, "keys");
} else {
  console.log("Could not find AR section start");
}
